### ISSUE TITLE
#Bug#shp炮塔建筑无法正确更新炮塔朝向，有时存在炮塔不显示的问题

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/FA2Copy#2]
【现象】：修改shp炮塔建筑朝向后，炮塔图像并不会更新到对应的方向，而是始终指向224方向。此外使用了Image=xxx的建筑会导致炮塔不显示
【反馈人】：
【发现版本号】：原版
【影响范围】：shp建筑炮塔
【产生原因】：shp炮塔逻辑缺陷

**Comment by secsome** [comment]
Already resolved
