### ISSUE TITLE
#Bug#特遣小队、脚本、作战小队修改名称时，每次输入都引起立即刷新所有控件，导致程序响应很慢

### ISSUE THREAD

**Issue by Zero-Fanker** [Zero-Fanker/FA2Copy#3]
【现象】：特遣小队、脚本、作战小队修改名称时，每次输入都引起立即刷新所有控件，导致程序响应很慢，而触发事件则是在修改的控件失焦时才更新。
【反馈人】：
【发现版本号】：原版
【影响范围】：涉及上述三个对话框名称变更时
【产生原因】：官方版使用了错误的事件关联导致刷新过于频繁，需要改为失焦检测

**Comment by secsome** [comment]
```

**Comment by secsome** [comment]
```C++
void CTeamTypesExt::ProgramStartupInit()
{
	RunTime::ResetMemoryContentAt(0x596D00 + 0x4, &RunTime::Messages::EDIT_KILLFOCUS, 4); // name update
	RunTime::ResetMemoryContentAt(0x596D30 + 0x4, &RunTime::Messages::COMBOBOX_KILLFOCUS, 4); // veteran update
	RunTime::ResetMemoryContentAt(0x596D48 + 0x4, &RunTime::Messages::COMBOBOX_KILLFOCUS, 4); // house update
	RunTime::ResetMemoryContentAt(0x596D60 + 0x4, &RunTime::Messages::EDIT_KILLFOCUS, 4); // priority update
	RunTime::ResetMemoryContentAt(0x596D78 + 0x4, &RunTime::Messages::EDIT_KILLFOCUS, 4); // max update
	RunTime::ResetMemoryContentAt(0x596D90 + 0x4, &RunTime::Messages::COMBOBOX_KILLFOCUS, 4); // techlevel update
	RunTime::ResetMemoryContentAt(0x596DA8 + 0x4, &RunTime::Messages::COMBOBOX_KILLFOCUS, 4); // group update
	RunTime::ResetMemoryContentAt(0x596DC0 + 0x4, &RunTime::Messages::COMBOBOX_KILLFOCUS, 4); // waypoint update
	RunTime::ResetMemoryContentAt(0x596DD8 + 0x4, &RunTime::Messages::COMBOBOX_KILLFOCUS, 4); // script update
	RunTime::ResetMemoryContentAt(0x596DF0 + 0x4, &RunTime::Messages::COMBOBOX_KILLFOCUS, 4); // taskforce update
	RunTime::ResetMemoryContentAt(0x5970C0 + 0x4, &RunTime::Messages::COMBOBOX_KILLFOCUS, 4); // tag update
	RunTime::ResetMemoryContentAt(0x5970F0 + 0x4, &RunTime::Messages::COMBOBOX_KILLFOCUS, 4); // transport waypoint update
	RunTime::ResetMemoryContentAt(0x597120 + 0x4, &RunTime::Messages::COMBOBOX_KILLFOCUS, 4); // mind control decision update
}
void CTaskForceExt::ProgramStartupInit()
{
    RunTime::ResetMemoryContentAt(0x596B38 + 0x4, &RunTime::Messages::EDIT_KILLFOCUS, 4); // name update
    RunTime::ResetMemoryContentAt(0x596B20 + 0x4, &RunTime::Messages::EDIT_KILLFOCUS, 4); // member count update
    RunTime::ResetMemoryContentAt(0x596BC8 + 0x4, &RunTime::Messages::EDIT_KILLFOCUS, 4); // group update
    RunTime::ResetMemoryContentAt(0x596B50 + 0x4, &RunTime::Messages::COMBOBOX_KILLFOCUS, 4); // member type update
}

void CScriptTypesExt::ProgramStartupInit()
{
 RunTime::ResetMemoryContentAt(0x595FC8 + 0x4, &RunTime::Messages::EDIT_KILLFOCUS, 4); // name update
    RunTime::ResetMemoryContentAt(0x596010 + 0x4, &RunTime::Messages::COMBOBOX_KILLFOCUS, 4); // param update
}
```

**Comment by Zero-Fanker** [comment]
> ```C++
> void CTeamTypesExt::ProgramStartupInit()
> {
> 	RunTime::ResetMemoryContentAt(0x596D00 + 0x4, &RunTime::Messages::EDIT_KILLFOCUS, 4); // name update
> 	RunTime::ResetMemoryContentAt(0x596D30 + 0x4, &RunTime::Messages::COMBOBOX_KILLFOCUS, 4); // veteran update
> 	RunTime::ResetMemoryContentAt(0x596D48 + 0x4, &RunTime::Messages::COMBOBOX_KILLFOCUS, 4); // house update
> 	RunTime::ResetMemoryContentAt(0x596D60 + 0x4, &RunTime::Messages::EDIT_KILLFOCUS, 4); // priority update
> 	RunTime::ResetMemoryContentAt(0x596D78 + 0x4, &RunTime::Messages::EDIT_KILLFOCUS, 4); // max update
> 	RunTime::ResetMemoryContentAt(0x596D90 + 0x4, &RunTime::Messages::COMBOBOX_KILLFOCUS, 4); // techlevel update
> 	RunTime::ResetMemoryContentAt(0x596DA8 + 0x4, &RunTime::Messages::COMBOBOX_KILLFOCUS, 4); // group update
> 	RunTime::ResetMemoryContentAt(0x596DC0 + 0x4, &RunTime::Messages::COMBOBOX_KILLFOCUS, 4); // waypoint update
> 	RunTime::ResetMemoryContentAt(0x596DD8 + 0x4, &RunTime::Messages::COMBOBOX_KILLFOCUS, 4); // script update
> 	RunTime::ResetMemoryContentAt(0x596DF0 + 0x4, &RunTime::Messages::COMBOBOX_KILLFOCUS, 4); // taskforce update
> 	RunTime::ResetMemoryContentAt(0x5970C0 + 0x4, &RunTime::Messages::COMBOBOX_KILLFOCUS, 4); // tag update
> 	RunTime::ResetMemoryContentAt(0x5970F0 + 0x4, &RunTime::Messages::COMBOBOX_KILLFOCUS, 4); // transport waypoint update
> 	RunTime::ResetMemoryContentAt(0x597120 + 0x4, &RunTime::Messages::COMBOBOX_KILLFOCUS, 4); // mind control decision update
> }
> void CTaskForceExt::ProgramStartupInit()
> {
>     RunTime::ResetMemoryContentAt(0x596B38 + 0x4, &RunTime::Messages::EDIT_KILLFOCUS, 4); // name update
>     RunTime::ResetMemoryContentAt(0x596B20 + 0x4, &RunTime::Messages::EDIT_KILLFOCUS, 4); // member count update
>     RunTime::ResetMemoryContentAt(0x596BC8 + 0x4, &RunTime::Messages::EDIT_KILLFOCUS, 4); // group update
>     RunTime::ResetMemoryContentAt(0x596B50 + 0x4, &RunTime::Messages::COMBOBOX_KILLFOCUS, 4); // member type update
> }
> 
> void CScriptTypesExt::ProgramStartupInit()
> {
>  RunTime::ResetMemoryContentAt(0x595FC8 + 0x4, &RunTime::Messages::EDIT_KILLFOCUS, 4); // name update
>     RunTime::ResetMemoryContentAt(0x596010 + 0x4, &RunTime::Messages::COMBOBOX_KILLFOCUS, 4); // param update
> }
> ```

你还不如直接把代码合入，另外别忘了Enter键的判定。

**Comment by secsome** [comment]
Already resolved
